name: Lint all Branches

on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dependency
        run: yarn install
      - name: Lint
        run: yarn lint
