name: Deploy Prod

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/deploy.yml
      with:
        heroku_app_name: 'svelte-kit-app'
